version: '3.8'
services:
  nestjs-taturial-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      -POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
    networks:
      - nestjs-taturial-network
networks:
  nestjs-taturial-network:
